import type { Category, Product } from "./types";

export const CATALOG_VERSION = "1.0.0";

export const FREE_SHIPPING_THRESHOLD = 49900;
export const SHIPPING_FEE = 4900;
export const STUDENT_DISCOUNT_CODE = "STUDENT10";
export const STUDENT_DISCOUNT_PCT = 10;
export const COUPONS: Record<string, { name: string; pct: number }> = {
  STUDENT10: { name: "Student 10%", pct: 10 },
  HACK10: { name: "Hackathon 10%", pct: 10 },
};

export const categories: Category[] = [
  {
    slug: "sensor-modules",
    name: "Sensors & Modules",
    tagline: "4000+ sensors in stock",
    description:
      "India's largest range of sensors — ultrasonic, IR, temperature, humidity, motion, gas, pressure and more. Every SKU tested for quality.",
    imageHue: "from-emerald-400 to-teal-600",
    emoji: "📡",
  },
  {
    slug: "development-boards",
    name: "Development Boards",
    tagline: "Arduino, ESP32, Raspberry Pi",
    description:
      "Microcontroller and SBC boards for every project — from your first blink to full AIoT builds. Originals and reliable clones.",
    imageHue: "from-sky-400 to-blue-600",
    emoji: "🔌",
  },
  {
    slug: "motors",
    name: "Motors, Drivers & Pumps",
    tagline: "DC, stepper, servo, BLDC",
    description:
      "Motors, motor drivers, gearboxes, pumps and actuators for robotics, automation and mechatronics projects.",
    imageHue: "from-orange-400 to-red-600",
    emoji: "⚙️",
  },
  {
    slug: "integrated-circuits",
    name: "Integrated Circuits",
    tagline: "ICs, MCUs, memory & logic",
    description:
      "Analog, digital and mixed-signal ICs from leading manufacturers — op-amps, regulators, drivers, memory and MCUs.",
    imageHue: "from-violet-400 to-purple-600",
    emoji: "🔬",
  },
  {
    slug: "displays",
    name: "Displays & LEDs",
    tagline: "OLED, LCD, TFT, 7-segment",
    description:
      "Screens for your build — from 0.96\" OLEDs to full TFT panels, plus LED strips, matrices and indicators.",
    imageHue: "from-pink-400 to-fuchsia-600",
    emoji: "🖥️",
  },
  {
    slug: "iot-wireless",
    name: "IoT & Wireless",
    tagline: "WiFi, BLE, LoRa, GSM, 433MHz",
    description:
      "Wireless connectivity modules and gateways to turn any device into an IoT endpoint — wherever you are.",
    imageHue: "from-indigo-400 to-violet-600",
    emoji: "📶",
  },
  {
    slug: "power",
    name: "Batteries & Power",
    tagline: "LiPo, 18650, PSU, solar",
    description:
      "Power your electronics — Li-ion/LiPo cells, chargers, power banks, bench power supplies, adapters and solar.",
    imageHue: "from-amber-400 to-yellow-600",
    emoji: "🔋",
  },
  {
    slug: "mechanical",
    name: "Mechanical & Tools",
    tagline: "Chassis, gears, fasteners & tools",
    description:
      "Structural parts, robotics hardware, precision tools and accessories to make your builds sturdy and pro.",
    imageHue: "from-slate-400 to-gray-600",
    emoji: "🛠️",
  },
  {
    slug: "diy-kits",
    name: "DIY & Project Kits",
    tagline: "Robotics, IoT, STEM kits",
    description:
      "Ready-to-build kits for competitions, hackathons and classrooms — everything included, no hunting for parts.",
    imageHue: "from-teal-400 to-emerald-600",
    emoji: "📦",
  },
  {
    slug: "3d-printing",
    name: "3D Printing & CNC",
    tagline: "Printers, filaments, parts",
    description:
      "3D printers, filaments in every colour, print heads, controllers and CNC accessories for makers.",
    imageHue: "from-rose-400 to-pink-600",
    emoji: "🗜️",
  },
];

export const products: Product[] = [
  // ---------- SENSORS & MODULES ----------
  {
    id: "p-sen-001",
    slug: "hc-sr04-ultrasonic-distance-sensor",
    name: "HC-SR04 Ultrasonic Distance Sensor",
    sku: "SEN-ULTR-HCSR04",
    brand: "Robu",
    categorySlug: "sensor-modules",
    price: 6900,
    mrp: 12000,
    inStock: true,
    stock: 340,
    rating: 4.5,
    reviewCount: 1832,
    featured: true,
    description:
      "The classic HC-SR04 ultrasonic ranging module measures 2cm to 4m with stable echoes. Essential for obstacle-avoiding robots, distance alarms and parking systems.",
    highlights: [
      "Measurement range: 2cm – 400cm",
      "Resolution: 0.3cm, accuracy ±3mm",
      "5V operation, TTL trigger & echo pins",
      "Wide detection cone for robot navigation",
    ],
    specs: [
      { label: "Working voltage", value: "5V DC" },
      { label: "Working current", value: "15mA" },
      { label: "Frequency", value: "40kHz" },
      { label: "Range", value: "2cm – 400cm" },
      { label: "Measuring angle", value: "15°" },
    ],
    tags: ["ultrasonic", "distance", "sensor", "robot", "hc-sr04"],
    imageHue: "from-emerald-400 to-teal-600",
    emoji: "📡",
  },
  {
    id: "p-sen-002",
    slug: "mpu6050-gyroscope-accelerometer",
    name: "MPU6050 6-Axis Gyro + Accelerometer",
    sku: "SEN-IMU-MPU6050",
    brand: "Robu",
    categorySlug: "sensor-modules",
    price: 14900,
    mrp: 25000,
    inStock: true,
    stock: 210,
    rating: 4.4,
    reviewCount: 967,
    description:
      "6-axis motion tracking all-in-one: 3-axis gyroscope + 3-axis accelerometer with I2C interface. Perfect for drones, self-balancing bots and orientation sensing.",
    highlights: [
      "Tri-axis gyro + tri-axis accelerometer",
      "I2C interface, 400kHz fast mode",
      "Embedded Digital Motion Processor (DMP)",
      "2.3V – 3.4V, low power",
    ],
    specs: [
      { label: "Axes", value: "6 (gyro + accel)" },
      { label: "Interface", value: "I2C (0x68 / 0x69)" },
      { label: "Gyro range", value: "±250 / ±500 / ±1000 / ±2000 °/s" },
      { label: "Accel range", value: "±2 / ±4 / ±8 / ±16 g" },
      { label: "Voltage", value: "2.3V – 3.4V" },
    ],
    tags: ["imu", "gyro", "accelerometer", "quadcopter", "mpu6050"],
    imageHue: "from-emerald-400 to-teal-600",
    emoji: "📡",
  },
  {
    id: "p-sen-003",
    slug: "dht22-temperature-humidity",
    name: "DHT22 AM2302 Temp & Humidity Sensor",
    sku: "SEN-ENV-DHT22",
    brand: "Robu",
    categorySlug: "sensor-modules",
    price: 19900,
    mrp: 32000,
    inStock: true,
    stock: 175,
    rating: 4.6,
    reviewCount: 1123,
    isNew: true,
    description:
      "High-precision digital temperature and humidity sensor with excellent accuracy across −40°C to 80°C. Weather stations, greenhouses, server-room monitors.",
    highlights: [
      "±0.5°C, ±2% RH accuracy",
      "−40°C to +80°C range",
      "Single-wire digital output",
      "3.3V – 5V supply",
    ],
    specs: [
      { label: "Temperature", value: "−40°C to 80°C (±0.5°C)" },
      { label: "Humidity", value: "0–100% RH (±2%)" },
      { label: "Output", value: "Digital, single bus" },
      { label: "Supply", value: "3.3V – 5V" },
      { label: "Sample rate", value: "0.5Hz" },
    ],
    tags: ["dht22", "temperature", "humidity", "weather", "environment"],
    imageHue: "from-emerald-400 to-teal-600",
    emoji: "📡",
  },
  {
    id: "p-sen-004",
    slug: "ir-obstacle-sensor-module",
    name: "IR Obstacle Avoidance Sensor Module",
    sku: "SEN-IR-OBST",
    brand: "Robu",
    categorySlug: "sensor-modules",
    price: 5900,
    mrp: 9900,
    inStock: true,
    stock: 420,
    rating: 4.3,
    reviewCount: 1544,
    featured: true,
    description:
      "Tiny IR proximity module with adjustable range (2–30cm) and digital TTL output. The go-to sensor for line-follower and obstacle-avoidance bot competitions.",
    highlights: [
      "Adjustable detection 2cm – 30cm",
      "Digital high/low TTL output",
      "Onboard indicator LED + potentiometer",
      "Works with any MCU, 3.3–5V",
    ],
    specs: [
      { label: "Range", value: "2 – 30cm (adjustable)" },
      { label: "Output", value: "Digital HIGH/LOW (TTL)" },
      { label: "Voltage", value: "3.3V – 5V" },
      { label: "Current", value: "20mA" },
      { label: "Size", value: "3.2 × 1.4cm" },
    ],
    tags: ["ir", "obstacle", "proximity", "line-follower", "robot"],
    imageHue: "from-emerald-400 to-teal-600",
    emoji: "📡",
  },

  // ---------- DEVELOPMENT BOARDS ----------
  {
    id: "p-brd-001",
    slug: "esp32-devkit-v1-wifi-bluetooth",
    name: "ESP32 DevKit V1 (WiFi + Bluetooth)",
    sku: "BRD-ESP32-DEVKIT",
    brand: "ESPresso",
    categorySlug: "development-boards",
    price: 34900,
    mrp: 55000,
    inStock: true,
    stock: 260,
    rating: 4.7,
    reviewCount: 2560,
    featured: true,
    isNew: true,
    description:
      "Dual-core 240MHz ESP32 development board with onboard WiFi + Bluetooth. The workhorse for IoT, robotics and hackathons — Arduino & MicroPython ready.",
    highlights: [
      "Dual-core Xtensa LX6 @ 240MHz",
      "WiFi 802.11 b/g/n + BLE 4.2",
      "4MB Flash, 520KB SRAM",
      "CP2102 USB, breadboard friendly",
    ],
    specs: [
      { label: "SoC", value: "ESP32-WROOM-32" },
      { label: "CPU", value: "Dual-core Xtensa LX6 @ 240MHz" },
      { label: "Wireless", value: "WiFi + Bluetooth 4.2" },
      { label: "Flash / SRAM", value: "4MB / 520KB" },
      { label: "GPIO", value: "30 pins (12-bit ADC)" },
    ],
    tags: ["esp32", "wifi", "bluetooth", "iot", "arduino"],
    imageHue: "from-sky-400 to-blue-600",
    emoji: "🔌",
  },
  {
    id: "p-brd-002",
    slug: "arduino-uno-r3",
    name: "Arduino UNO R3 (Original)",
    sku: "BRD-ARDUINO-UNO",
    brand: "Arduino",
    categorySlug: "development-boards",
    price: 59900,
    mrp: 89900,
    inStock: true,
    stock: 95,
    rating: 4.8,
    reviewCount: 3201,
    featured: true,
    description:
      "The legendary Arduino UNO R3 with ATMega328P. The most documented board on Earth — the safest choice for students, colleges and competitions.",
    highlights: [
      "ATmega328P-AU microcontroller",
      "14 digital I/O, 6 analog inputs",
      "USB programming, 16MHz",
      "Vast ecosystem & tutorials",
    ],
    specs: [
      { label: "MCU", value: "ATmega328P" },
      { label: "Operating voltage", value: "5V" },
      { label: "Digital I/O", value: "14 (6 PWM)" },
      { label: "Analog inputs", value: "6" },
      { label: "Clock", value: "16MHz" },
      { label: "Flash", value: "32KB" },
    ],
    tags: ["arduino", "uno", "microcontroller", "beginner", "hackathon"],
    imageHue: "from-sky-400 to-blue-600",
    emoji: "🔌",
  },
  {
    id: "p-brd-003",
    slug: "raspberry-pi-4-model-b",
    name: "Raspberry Pi 4 Model B (8GB)",
    sku: "BRD-RPI4-8GB",
    brand: "Raspberry Pi",
    categorySlug: "development-boards",
    price: 749900,
    mrp: 799900,
    inStock: true,
    stock: 42,
    rating: 4.9,
    reviewCount: 1875,
    description:
      "Full single-board computer with quad-core Cortex-A72, 8GB RAM, dual HDMI 4K and gigabit Ethernet — runs Linux, Docker, ML and robotics stacks.",
    highlights: [
      "Quad-core Cortex-A72 @ 1.5GHz",
      "8GB LPDDR4 RAM",
      "Dual micro-HDMI 4K60, GbE, USB3",
      "WiFi 5 + BLE 5.0",
    ],
    specs: [
      { label: "CPU", value: "Broadcom BCM2711, 4× Cortex-A72" },
      { label: "RAM", value: "8GB LPDDR4" },
      { label: "Video", value: "Dual 4K micro-HDMI" },
      { label: "Networking", value: "GbE, 2.4/5GHz WiFi, BLE" },
      { label: "USB", value: "2× USB 3.0, 2× USB 2.0" },
    ],
    tags: ["raspberry-pi", "sbc", "linux", "ai", "computer"],
    imageHue: "from-sky-400 to-blue-600",
    emoji: "🔌",
  },
  {
    id: "p-brd-004",
    slug: "nodemcu-esp8266-wifi",
    name: "NodeMCU ESP8266 (WiFi)",
    sku: "BRD-NODEMCU-ESP",
    brand: "LoLin",
    categorySlug: "development-boards",
    price: 14900,
    mrp: 25000,
    inStock: true,
    stock: 300,
    rating: 4.4,
    reviewCount: 2201,
    description:
      "EasyWiFi NodeMCU board with CP2102 and micro-USB. Perfect budget IoT brain for students — great community, tons of sample code.",
    highlights: [
      "ESP8266 + on-board WiFi",
      "CP2102 USB-serial, plug & play",
      "4MB flash, Arduino IDE ready",
      "Great for IoT learning",
    ],
    specs: [
      { label: "SoC", value: "ESP8266 @ 80/160MHz" },
      { label: "Wireless", value: "WiFi 802.11 b/g/n" },
      { label: "Flash", value: "4MB" },
      { label: "Pins", value: "11 digital, 1 analog" },
      { label: "USB", value: "Micro-USB (CP2102)" },
    ],
    tags: ["nodemcu", "esp8266", "wifi", "iot", "student"],
    imageHue: "from-sky-400 to-blue-600",
    emoji: "🔌",
  },

  // ---------- MOTORS & DRIVERS ----------
  {
    id: "p-mot-001",
    slug: "l298n-motor-driver-module",
    name: "L298N Dual H-Bridge Motor Driver",
    sku: "MOT-DRV-L298N",
    brand: "Robu",
    categorySlug: "motors",
    price: 11900,
    mrp: 19900,
    inStock: true,
    stock: 230,
    rating: 4.5,
    reviewCount: 1980,
    featured: true,
    description:
      "The classic dual H-bridge module driving two DC motors or one stepper (up to 2A per channel). Onboard 5V regulator — the driver behind most robot cars.",
    highlights: [
      "Drives 2× DC or 1× stepper",
      "2A peak per channel, 5–35V",
      "Onboard 5V regulator",
      "TTL-compatible PWM control",
    ],
    specs: [
      { label: "Channels", value: "2 (dual H-bridge)" },
      { label: "Motor voltage", value: "5V – 35V" },
      { label: "Current", value: "2A per channel" },
      { label: "Logic", value: "5V TTL" },
      { label: "Size", value: "43 × 43mm" },
    ],
    tags: ["l298n", "motor driver", "robot car", "stepper", "h-bridge"],
    imageHue: "from-orange-400 to-red-600",
    emoji: "⚙️",
  },
  {
    id: "p-mot-002",
    slug: "sg90-micro-servo",
    name: "SG90 TowerPro Micro Servo (9g)",
    sku: "MOT-SRV-SG90",
    brand: "TowerPro",
    categorySlug: "motors",
    price: 6900,
    mrp: 12000,
    inStock: true,
    stock: 500,
    rating: 4.4,
    reviewCount: 3420,
    featured: true,
    description:
      "Pocket-size 9g plastic-gear servo doing 180° rotation with ~1.8kg-cm torque. The default choice for robot arms, pan-tilt and RC projects.",
    highlights: [
      "9g, 1.8kg-cm torque @ 4.8V",
      "180° ± 10° rotation",
      "PWM control (50Hz)",
      "Mini + standard arms included",
    ],
    specs: [
      { label: "Torque", value: "1.8 kg-cm @ 4.8V" },
      { label: "Speed", value: "0.1s/60°" },
      { label: "Voltage", value: "4.8V – 6V" },
      { label: "Weight", value: "9g" },
      { label: "Gear", value: "Plastic" },
    ],
    tags: ["servo", "sg90", "robot arm", "rc", "micro"],
    imageHue: "from-orange-400 to-red-600",
    emoji: "⚙️",
  },
  {
    id: "p-mot-003",
    slug: "28byj-48-stepper-motor-uln2003",
    name: "28BYJ-48 Stepper Motor with ULN2003 Driver",
    sku: "MOT-STP-28BYJ",
    brand: "Robu",
    categorySlug: "motors",
    price: 11900,
    mrp: 19900,
    inStock: true,
    stock: 310,
    rating: 4.4,
    reviewCount: 1540,
    description:
      "5V unipolar stepper with 32-step gearbox giving 64:1 reduction — smooth precision rotation for camera turrets, CNC, and 3D printer Z-axes.",
    highlights: [
      "5V, 4-phase unipolar stepper",
      "ULN2003 driver board included",
      "64:1 gearbox, ~2048 steps/rev",
      "Ideal for slow precise motion",
    ],
    specs: [
      { label: "Voltage", value: "5V DC" },
      { label: "Steps/rev", value: "~2048 (5.625°/64)" },
      { label: "Torque", value: "2.2 kg-cm" },
      { label: "Driver", value: "ULN2003" },
      { label: "Current", value: "100mA/phase" },
    ],
    tags: ["stepper", "28byj-48", "uln2003", "cnc", "turret"],
    imageHue: "from-orange-400 to-red-600",
    emoji: "⚙️",
  },
  {
    id: "p-mot-004",
    slug: "n20-gear-micromotor-12v",
    name: "N20 Micro Gear Motor (12V, with Encoder)",
    sku: "MOT-MINI-N20-ENC",
    brand: "Robu",
    categorySlug: "motors",
    price: 19900,
    mrp: 32000,
    inStock: true,
    stock: 140,
    rating: 4.5,
    reviewCount: 620,
    isNew: true,
    description:
      "Tiny 1000RPM geared DC motor with hall-effect encoder feedback — dead-simple closed-loop control for mini line followers and smart vehicles.",
    highlights: [
      "12V N20 gear motor",
      "Hall encoder for speed feedback",
      "Compact 10mm footprint",
      "Great for mini robots",
    ],
    specs: [
      { label: "Voltage", value: "6V – 12V" },
      { label: "Rated speed", value: "~1000 RPM @ 12V" },
      { label: "Encoder", value: "Hall effect (2× pulses)" },
      { label: "Weight", value: "~10g" },
      { label: "Shaft", value: "3mm D-type + gearhead" },
    ],
    tags: ["n20", "gearmotor", "encoder", "mini robot", "speed control"],
    imageHue: "from-orange-400 to-red-600",
    emoji: "⚙️",
  },

  // ---------- ICs ----------
  {
    id: "p-ic-001",
    slug: "ne555-timer-ic",
    name: "NE555 Timer IC (DIP-8)",
    sku: "IC-TMR-NE555",
    brand: "TI",
    categorySlug: "integrated-circuits",
    price: 1490,
    mrp: 3000,
    inStock: true,
    stock: 1200,
    rating: 4.5,
    reviewCount: 876,
    description:
      "The world's most popular timer IC. Astable/monostable oscillators, PWM generation, delays and pulses — a staple of every electronics lab.",
    highlights: [
      "Astable & monostable timer",
      "4.5V – 16V operation",
      "200mA output drive",
      "DIP-8, breadboard friendly",
    ],
    specs: [
      { label: "Type", value: "NE555N, DIP-8" },
      { label: "Supply", value: "4.5V – 16V" },
      { label: "Output current", value: "200mA" },
      { label: "Frequency", value: "Up to 500kHz" },
      { label: "Package", value: "8-Pin DIP" },
    ],
    tags: ["ne555", "timer", "ic", "oscillator", "pwm"],
    imageHue: "from-violet-400 to-purple-600",
    emoji: "🔬",
  },
  {
    id: "p-ic-002",
    slug: "lm358-dual-opamp",
    name: "LM358 Dual Op-Amp IC (DIP-8)",
    sku: "IC-AMP-LM358",
    brand: "TI",
    categorySlug: "integrated-circuits",
    price: 1190,
    mrp: 2500,
    inStock: true,
    stock: 900,
    rating: 4.3,
    reviewCount: 430,
    webOnly: true,
    description:
      "Two high-gain op-amps in one DIP-8 package running off a single supply — amplify sensor signals, build comparators and signal conditioners.",
    highlights: [
      "Dual op-amp, single supply",
      "3V – 32V operation",
      "True differential inputs",
      "Short-circuit protected",
    ],
    specs: [
      { label: "Type", value: "LM358N, DIP-8" },
      { label: "Amps", value: "2 per package" },
      { label: "Supply", value: "3V – 32V (single)" },
      { label: "GBW", value: "1MHz" },
      { label: "Package", value: "8-Pin DIP" },
    ],
    tags: ["lm358", "opamp", "amplifier", "comparator", "signal"],
    imageHue: "from-violet-400 to-purple-600",
    emoji: "🔬",
  },
  {
    id: "p-ic-003",
    slug: "lm2596-buck-converter-module",
    name: "LM2596 Buck Converter Module (3A)",
    sku: "IC-PWR-LM2596",
    brand: "Robu",
    categorySlug: "integrated-circuits",
    price: 7900,
    mrp: 14900,
    inStock: true,
    stock: 420,
    rating: 4.6,
    reviewCount: 2100,
    isNew: true,
    description:
      "Step-down DC-DC module from 3.2–40V input to 1.25–37V output at up to 3A with 90% efficiency. The standard regulator for robot power rails.",
    highlights: [
      "Input 3.2V – 40V, output 1.25V – 37V",
      "Up to 3A continuous, 92% efficiency",
      "Trim potentiometer output",
      "Overcurrent & thermal protection",
    ],
    specs: [
      { label: "Input", value: "3.2V – 40V DC" },
      { label: "Output", value: "1.25V – 37V (adjustable)" },
      { label: "Current", value: "3A (peak 5A)" },
      { label: "Efficiency", value: "Up to 92%" },
      { label: "Board", value: "43 × 21mm" },
    ],
    tags: ["lm2596", "buck", "dc-dc", "power", "voltage regulator"],
    imageHue: "from-violet-400 to-purple-600",
    emoji: "🔬",
  },
  {
    id: "p-ic-004",
    slug: "atmega328p-pu-microcontroller",
    name: "ATmega328P-PU AVR MCU",
    sku: "IC-MCU-328P",
    brand: "Microchip",
    categorySlug: "integrated-circuits",
    price: 12900,
    mrp: 24900,
    inStock: true,
    stock: 350,
    rating: 4.7,
    reviewCount: 890,
    description:
      "The 8-bit AVR brain of the Arduino UNO as a raw DIP MCU. Flash your own programs and build clean, compact circuits without a dev board.",
    highlights: [
      "32KB flash, 2KB SRAM",
      "1.8V – 5.5V, 6 PWM channels",
      "8× 10-bit ADC channels",
      "DIP-28 for breadboards",
    ],
    specs: [
      { label: "Core", value: "AVR 8-bit" },
      { label: "Flash / SRAM / EEPROM", value: "32KB / 2KB / 1KB" },
      { label: "Clock", value: "Up to 20MHz" },
      { label: "Pins", value: "28-DIP" },
      { label: "Voltage", value: "1.8V – 5.5V" },
    ],
    tags: ["atmega328", "mcu", "avr", "dip", "arduino"],
    imageHue: "from-violet-400 to-purple-600",
    emoji: "🔬",
  },

  // ---------- DISPLAYS ----------
  {
    id: "p-dsp-001",
    slug: "ssd1306-oled-0-96-i2c",
    name: "0.96\" SSD1306 OLED Display (I2C)",
    sku: "DSP-OLED-096-I2C",
    brand: "Robu",
    categorySlug: "displays",
    price: 14900,
    mrp: 25000,
    inStock: true,
    stock: 320,
    rating: 4.6,
    reviewCount: 1780,
    featured: true,
    description:
      "Crisp 128×64 monochrome OLED with super-sharp contrast and wide viewing angle. Tiny current draw — the classic display for custom status readouts.",
    highlights: [
      "128×64, 0.96\" OLED, I2C",
      "No backlight — ultra thin",
      "~0.08W power draw",
      "Blue or white pixels",
    ],
    specs: [
      { label: "Resolution", value: "128 × 64" },
      { label: "Driver", value: "SSD1306" },
      { label: "Interface", value: "I2C (0x3C)" },
      { label: "Supply", value: "3.3V – 5V" },
      { label: "Size", value: "27 × 27mm" },
    ],
    tags: ["oled", "ssd1306", "display", "i2c", "status screen"],
    imageHue: "from-pink-400 to-fuchsia-600",
    emoji: "🖥️",
  },
  {
    id: "p-dsp-002",
    slug: "1-8-tft-lcd-touch",
    name: "1.8\" TFT LCD Display (ST7735, SPI)",
    sku: "DSP-TFT-18-SPI",
    brand: "Adafruit",
    categorySlug: "displays",
    price: 24900,
    mrp: 39900,
    inStock: true,
    stock: 120,
    rating: 4.4,
    reviewCount: 640,
    isNew: true,
    description:
      "Full-colour 160×128 TFT with glass face and SD slot. Touch-screen UIs, dashboards and mini games over a fast SPI interface.",
    highlights: [
      "160×128 RGB, ST7735",
      "Fast SPI, 18-bit colour",
      "SD card socket on board",
      "Great for UIs & games",
    ],
    specs: [
      { label: "Resolution", value: "160 × 128" },
      { label: "Driver", value: "ST7735R" },
      { label: "Interface", value: "SPI" },
      { label: "Supply", value: "3.3V / 5V logic" },
      { label: "Extras", value: "Micro-SD slot, glass cap" },
    ],
    tags: ["tft", "lcd", "st7735", "spi", "touch ui"],
    imageHue: "from-pink-400 to-fuchsia-600",
    emoji: "🖥️",
  },
  {
    id: "p-dsp-003",
    slug: "tm1637-4-digit-display",
    name: "TM1637 4-Digit 7-Segment Display",
    sku: "DSP-7SEG-TM1637",
    brand: "Robu",
    categorySlug: "displays",
    price: 9900,
    mrp: 18000,
    inStock: true,
    stock: 260,
    rating: 4.5,
    reviewCount: 980,
    description:
      "Bright red 4-digit display module — clock, counter, sensor readouts with only 2 data pins. Perfect for Arduino hobby builds.",
    highlights: [
      "4-digit red, 8-segment",
      "2-wire (CLK/DIO) interface",
      "Colon for clock display",
      "5V, ~30mA draw",
    ],
    specs: [
      { label: "Digits", value: "4 × 7-segment + colon" },
      { label: "Driver", value: "TM1637" },
      { label: "Interface", value: "2-wire (CLK, DIO)" },
      { label: "Supply", value: "3.3V – 5V" },
      { label: "Size", value: "42 × 24mm" },
    ],
    tags: ["tm1637", "7 segment", "display", "clock", "arduino"],
    imageHue: "from-pink-400 to-fuchsia-600",
    emoji: "🖥️",
  },
  {
    id: "p-dsp-004",
    slug: "ws2812b-led-strip-1m",
    name: "WS2812B RGB LED Strip (1m, 60 LEDs)",
    sku: "DSP-LED-WS2812B-1M",
    brand: "Robu",
    categorySlug: "displays",
    price: 24900,
    mrp: 45000,
    inStock: true,
    stock: 180,
    rating: 4.7,
    reviewCount: 1420,
    featured: true,
    description:
      "Addressable RGB LED strip — each LED individually controllable through a single wire. Ambient lighting, art displays and eye-catching builds.",
    highlights: [
      "60 RGB LEDs per metre",
      "Single-wire data control",
      "16.7M colours, addresable",
      "5V, cut-able every segment",
    ],
    specs: [
      { label: "LEDs", value: "60 / metre (WS2812B)" },
      { label: "Interface", value: "Single-wire (DIN)" },
      { label: "Supply", value: "5V DC" },
      { label: "Colours", value: "16.7M (24-bit)" },
      { label: "Strip", value: "1m, 10mm wide" },
    ],
    tags: ["ws2812b", "rgb", "led strip", "neopixel", "lighting"],
    imageHue: "from-pink-400 to-fuchsia-600",
    emoji: "🖥️",
  },

  // ---------- IOT & WIRELESS ----------
  {
    id: "p-iot-001",
    slug: "lora-sx1278-433mhz",
    name: "SX1278 LoRa Module (433MHz) + Antenna",
    sku: "IOT-LORA-SX1278",
    brand: "Ai-Thinker",
    categorySlug: "iot-wireless",
    price: 24900,
    mrp: 40000,
    inStock: true,
    stock: 110,
    rating: 4.6,
    reviewCount: 520,
    isNew: true,
    description:
      "Long-range LoRa transceiver reaching 1–15km line-of-sight at low power — sensor networks, village connectivity, and rural IoT builds.",
    highlights: [
      "433MHz, SPI controlled",
      "1–15km range (LOS)",
      "Ultra-low power receiver",
      "Antenna included",
    ],
    specs: [
      { label: "Frequency", value: "433MHz (ISM)" },
      { label: "Module", value: "SX1278" },
      { label: "Range", value: "1 – 15km (line of sight)" },
      { label: "Interface", value: "SPI" },
      { label: "Supply", value: "3.3V" },
    ],
    tags: ["lora", "sx1278", "long range", "433mhz", "sensor network"],
    imageHue: "from-indigo-400 to-violet-600",
    emoji: "📶",
  },
  {
    id: "p-iot-002",
    slug: "hc-05-bluetooth-module",
    name: "HC-05 Bluetooth Serial Module",
    sku: "IOT-BLE-HC05",
    brand: "Robu",
    categorySlug: "iot-wireless",
    price: 9900,
    mrp: 19000,
    inStock: true,
    stock: 280,
    rating: 4.3,
    reviewCount: 1890,
    description:
      "Bluetooth 2.0 serial bridge (UART to BLE) for wireless programming & phone control of robot cars, lights and instruments.",
    highlights: [
      "Classic BT / BLE 4.0",
      "UART (9600 baud) bridge",
      "AT command configurable",
      "Range ~10m",
    ],
    specs: [
      { label: "Bluetooth", value: "v2.0 SPP (HC-05)" },
      { label: "Interface", value: "UART (9600 default)" },
      { label: "Range", value: "~10m" },
      { label: "Supply", value: "3.3V – 6V" },
      { label: "Mode", value: "Master/slave configurable" },
    ],
    tags: ["hc-05", "bluetooth", "uart", "robot car", "phone control"],
    imageHue: "from-indigo-400 to-violet-600",
    emoji: "📶",
  },
  {
    id: "p-iot-003",
    slug: "gsm-sim800l-module",
    name: "SIM800L GSM/GPRS Module",
    sku: "IOT-GSM-SIM800L",
    brand: "SIMCom",
    categorySlug: "iot-wireless",
    price: 17900,
    mrp: 30000,
    inStock: true,
    stock: 90,
    rating: 4.3,
    reviewCount: 760,
    description:
      "Cellular voice + SMS + GPRS module on a tiny board — SMS alerts, trackers and connected alarms that need no WiFi.",
    highlights: [
      "Live 2G voice & SMS",
      "GPRS nternet (SIM needed)",
      "Tiny 17.8×15.8mm",
      "AT command control",
    ],
    specs: [
      { label: "Bands", value: "GSM 850/900/1800/1900" },
      { label: "Interfaces", value: "UART AT commands" },
      { label: "Voice", value: "Mic & speaker pins" },
      { label: "Supply", value: "3.4V – 4.4V (2A peak)" },
      { label: "Micro-SIM", value: "Included slot + tray" },
    ],
    tags: ["sim800l", "gsm", "sms", "gprs", "tracker"],
    imageHue: "from-indigo-400 to-violet-600",
    emoji: "📶",
  },
  {
    id: "p-iot-004",
    slug: "wifi-esp01-relay-4ch",
    name: "4-Channel WiFi Relay Board (ESP-01)",
    sku: "IOT-RELAY-4CH-WIFI",
    brand: "Robu",
    categorySlug: "iot-wireless",
    price: 39900,
    mrp: 65000,
    inStock: true,
    stock: 130,
    rating: 4.5,
    reviewCount: 830,
    featured: true,
    description:
      "Control 4 home appliances over WiFi through ESP-01 with opto-isolated relays up to 250V/10A. Home automation in an afternoon.",
    highlights: [
      "4× SPDT relays, 10A/250V",
      "WiFi control via ESP-01",
      "Opto-isolated inputs",
      "Red + Green status LEDs",
    ],
    specs: [
      { label: "Relays", value: "4× SPDT 10A/250VAC" },
      { label: "Module", value: "ESP-01 (WiFi)" },
      { label: "Isolation", value: "Optocoupler" },
      { label: "Supply", value: "7V – 12V DC" },
      { label: "Pins", value: "GPIO0/GPIO2 triggers" },
    ],
    tags: ["relay", "wifi", "esp-01", "home automation", "4 channel"],
    imageHue: "from-indigo-400 to-violet-600",
    emoji: "📶",
  },

  // ---------- POWER ----------
  {
    id: "p-pwr-001",
    slug: "18650-li-ion-3000mah",
    name: "18650 Li-Ion Cell 3000mAh (3.7V)",
    sku: "PWR-18650-3000",
    brand: "Panasonic",
    categorySlug: "power",
    price: 24900,
    mrp: 40000,
    inStock: true,
    stock: 240,
    rating: 4.6,
    reviewCount: 1230,
    featured: true,
    description:
      "Genuine 18650 cell with 3000mAh capacity and 10A discharge — the rechargeable heart of power banks, lanterns and robot power packs.",
    highlights: [
      "3000mAh NCR18650B",
      "10A max discharge",
      "~500 charge cycles",
      "Flat top, protected option",
    ],
    specs: [
      { label: "Capacity", value: "3000mAh" },
      { label: "Voltage", value: "3.7V nominal (4.2V max)" },
      { label: "Discharge", value: "10A max" },
      { label: "Chemistry", value: "Li-Ion NCA" },
      { label: "Size", value: "18 × 65mm" },
    ],
    tags: ["18650", "li-ion", "battery", "power bank", "3.7v"],
    imageHue: "from-amber-400 to-yellow-600",
    emoji: "🔋",
  },
  {
    id: "p-pwr-002",
    slug: "tp4056-lipo-charger-module",
    name: "TP4056 LiPo Charger Module (Type-C)",
    sku: "PWR-CHG-TP4056",
    brand: "Robu",
    categorySlug: "power",
    price: 4900,
    mrp: 9990,
    inStock: true,
    stock: 460,
    rating: 4.5,
    reviewCount: 2210,
    description:
      "USB-C 1A charger with DW01 battery protection for single 3.7V cells. The tiny board that safely spices up every lithium project.",
    highlights: [
      "USB-C 1A charge current",
      "DW01A + FS8205 protection",
      "CHRG/STDBY LED indicators",
      "3.7V cell, 1S",
    ],
    specs: [
      { label: "Input", value: "5V via USB-C" },
      { label: "Charge current", value: "1A (selectable)" },
      { label: "Cell", value: "3.7V Li-Ion/LiPo (1S)" },
      { label: "Protection", value: "Over-charge/discharge/current" },
      { label: "Size", value: "26 × 17mm" },
    ],
    tags: ["tp4056", "charger", "lipo", "usb-c", "protection"],
    imageHue: "from-amber-400 to-yellow-600",
    emoji: "🔋",
  },
  {
    id: "p-pwr-003",
    slug: "9v-2a-adaptor",
    name: "9V 2A DC Switching Adaptor",
    sku: "PWR-ADP-9V2A",
    brand: "Robu",
    categorySlug: "power",
    price: 14900,
    mrp: 24900,
    inStock: true,
    stock: 190,
    rating: 4.4,
    reviewCount: 870,
    webOnly: true,
    description:
      "Reliable 9V 2A switch-mode adaptor with universal pin kit — power your Arduino, routers, fans and LED projects from the mains.",
    highlights: [
      "9V 2A (18W) SMPS",
      "8 tip adaptor set + barrel",
      "Indoor mains (100–240V)",
      "Overload & short protection",
    ],
    specs: [
      { label: "Output", value: "9V DC 2A (18W)" },
      { label: "Input", value: "100 – 240V AC 50/60Hz" },
      { label: "Cable", value: "1m DC cable" },
      { label: "Tips", value: "8 universal bits" },
      { label: "Output jack", value: "5.5×2.1mm (free tips)" },
    ],
    tags: ["9v", "adaptor", "power supply", "smps", "dc"],
    imageHue: "from-amber-400 to-yellow-600",
    emoji: "🔋",
  },
  {
    id: "p-pwr-004",
    slug: "7-4v-2s-lipo-1200mah",
    name: "7.4V 2S LiPo Battery 1200mAh 25C",
    sku: "PWR-LIPO-2S1200",
    brand: "Robu",
    categorySlug: "power",
    price: 39900,
    mrp: 65000,
    inStock: true,
    stock: 85,
    rating: 4.6,
    reviewCount: 640,
    isNew: true,
    description:
      "Compact 2S LiPo with XT60 + JST leads delivering 30A bursts — the standard battery inside smart robot cars and RC builds.",
    highlights: [
      "7.4V, 1200mAh, 25C",
      "XT60 + balance + JST leads",
      "High-drain LiPo chemistry",
      "Weighs only 68g",
    ],
    specs: [
      { label: "Voltage", value: "7.4V (2S)" },
      { label: "Capacity", value: "1200mAh" },
      { label: "C-rating", value: "25C (30A burst)" },
      { label: "Connectors", value: "XT60 + JST + balance" },
      { label: "Weight", value: "68g" },
    ],
    tags: ["lipo", "2s", "7.4v", "robot car", "high drain"],
    imageHue: "from-amber-400 to-yellow-600",
    emoji: "🔋",
  },

  // ---------- MECHANICAL ----------
  {
    id: "p-mch-001",
    slug: "robot-car-chassis-4wd",
    name: "4WD Smart Robot Car Chassis Kit",
    sku: "MECH-CHASS-4WD",
    brand: "Robu",
    categorySlug: "mechanical",
    price: 14900,
    mrp: 25000,
    inStock: true,
    stock: 220,
    rating: 4.4,
    reviewCount: 1890,
    featured: true,
    description:
      "Complete 4-wheel robot chassis with geared motors, wheels and caster — acrylic body ready to bolt your Arduino and sensors onto.",
    highlights: [
      "4× geared motors + wheels",
      "Acrylic stacked plates",
      "Universal caster wheel",
      "All nuts & bolts included",
    ],
    specs: [
      { label: "Drive", value: "4WD (2× pairs, gearheads)" },
      { label: "Wheels", value: "4× 2.6\" rubber" },
      { label: "Chassis", value: "Acrylic, expandable" },
      { label: "Battery", value: "Holds 6× AA" },
      { label: "Size", value: "195mm × 100mm" },
    ],
    tags: ["chassis", "robot car", "4wd", "kit", "acrylic"],
    imageHue: "from-slate-400 to-gray-600",
    emoji: "🛠️",
  },
  {
    id: "p-mch-002",
    slug: "metallic-gears-combo",
    name: "Robotic Arm Gear Combo (Metallic)",
    sku: "MECH-GEAR-COMBO",
    brand: "Robu",
    categorySlug: "mechanical",
    price: 19900,
    mrp: 34900,
    inStock: true,
    stock: 145,
    rating: 4.3,
    reviewCount: 320,
    description:
      "Precision metal gears, shaft collars and 3mm couplings — build sturdy robotic arms, turrets and winch mechanisms.",
    highlights: [
      "Zinc alloy spur gears set",
      "Shaft collars + 5mm couplings",
      "3mm D-shaft friendly",
      "Great for servo arms",
    ],
    specs: [
      { label: "Gears", value: "Mixed zinc-alloy set" },
      { label: "Couplings", value: "5mm × 3mm" },
      { label: "Collars", value: "3mm & 5mm" },
      { label: "Shafts", value: "3mm D-type ready" },
      { label: "Use", value: "Robot arms, winches" },
    ],
    tags: ["gears", "robotic arm", "coupling", "metal", "screw"],
    imageHue: "from-slate-400 to-gray-600",
    emoji: "🛠️",
  },
  {
    id: "p-mch-003",
    slug: "m3-screw-nut-standoff-kit",
    name: "M3 Screw, Nut & Standoff Kit (500 pc)",
    sku: "MECH-FAST-M3KIT",
    brand: "Robu",
    categorySlug: "mechanical",
    price: 24900,
    mrp: 45000,
    inStock: true,
    stock: 300,
    rating: 4.7,
    reviewCount: 940,
    featured: true,
    description:
      "Starter fastener kit: M3 screws of 6 lengths, nuts, threaded nylon standoffs and spacers — keep every project put together.",
    highlights: [
      "500 mixed fasteners",
      "Nylon + steel standoffs",
      "6 screw lengths (4-25mm)",
      "Labelled compartmental box",
    ],
    specs: [
      { label: "Screws", value: "M3 (6 lengths, 300 pcs)" },
      { label: "Nuts", value: "M3 (100 pcs)" },
      { label: "Standoffs", value: "Metal + nylon M-F" },
      { label: "Spacers", value: "Nylon assortd" },
      { label: "Box", value: "12-compartment" },
    ],
    tags: ["m3", "screw", "standoff", "fastener", "kit"],
    imageHue: "from-slate-400 to-gray-600",
    emoji: "🛠️",
  },
  {
    id: "p-mch-004",
    slug: "linear-slide-rail-300mm",
    name: "Linear Slide Rail 300mm (MGN12)",
    sku: "MECH-LIN-MGN12",
    brand: "Robu",
    categorySlug: "mechanical",
    price: 29900,
    mrp: 49900,
    inStock: true,
    stock: 60,
    rating: 4.5,
    reviewCount: 210,
    isNew: true,
    description:
      "MGN12 mini linear guide for 3D printers and CNCs — smooth precision motion on the Z and X axes with no backlash.",
    highlights: [
      "MGN12H carriage",
      "300mm hardened rail",
      "Low friction, quiet",
      "For CNC / 3D printers",
    ],
    specs: [
      { label: "Rail", value: "MGN12, 300mm" },
      { label: "Block", value: "MGN12H" },
      { label: "Tolerance", value: "High precision H" },
      { label: "Cheap", value: "52g rail + 18g block" },
      { label: "Use", value: "3D printers, CNC" },
    ],
    tags: ["linear rail", "mgn12", "guide", "cnc", "3d printer"],
    imageHue: "from-slate-400 to-gray-600",
    emoji: "🛠️",
  },

  // ---------- DIY & KITS ----------
  {
    id: "p-kit-001",
    slug: "line-follower-robot-combo",
    name: "Line Follower Robot Combo (Arduino)",
    sku: "KIT-LINE-ARD",
    brand: "Robu",
    categorySlug: "diy-kits",
    price: 149900,
    mrp: 249900,
    inStock: true,
    stock: 34,
    rating: 4.6,
    reviewCount: 420,
    featured: true,
    isNew: true,
    description:
      "Everything for a competition-ready line follower: chassis, Arduino, motor driver, 3 IR sensors, wheels, LiPo and a written guide. Add sensors later — win today.",
    highlights: [
      "Complete kit, no hunting",
      "3× IR sensors for smooth tracking",
      "Arduino + L298N + motors included",
      "Assembly guide + sample code",
    ],
    specs: [
      { label: "Includes", value: "Chassis, Arduino UNO, L298N" },
      { label: "Sensors", value: "3× IR line sensors" },
      { label: "Power", value: "7.4V LiPo + charger" },
      { label: "Skill", value: "Beginner friendly" },
      { label: "Use", value: "Techfest line follower" },
    ],
    tags: ["line follower", "kit", "arduino", "competition", "robot"],
    imageHue: "from-teal-400 to-emerald-600",
    emoji: "📦",
  },
  {
    id: "p-kit-002",
    slug: "iot-starter-kit-esp32",
    name: "IoT Starter Kit with ESP32 (20 parts)",
    sku: "KIT-IOT-ESP32",
    brand: "Robu",
    categorySlug: "diy-kits",
    price: 99900,
    mrp: 179900,
    inStock: true,
    stock: 78,
    rating: 4.7,
    reviewCount: 760,
    featured: true,
    description:
      "The fastest way into connected hardware: ESP32 plus sensors, actuators, breadboard and shows 12 ready projects with the code hosted freely.",
    highlights: [
      "ESP32 + 20 components",
      "12 guided IoT projects",
      "Breadboard, LEDs, buzzers, sensors",
      "Free code + diagrams online",
    ],
    specs: [
      { label: "Board", value: "ESP32 DevKit V1" },
      { label: "Parts", value: "20 components" },
      { label: "Projects", value: "12 with code" },
      { label: "Skill", value: "Beginner" },
      { label: "Extras", value: "Breadboard + jumpers" },
    ],
    tags: ["iot", "kit", "esp32", "starter", "school"],
    imageHue: "from-teal-400 to-emerald-600",
    emoji: "📦",
  },
  {
    id: "p-kit-003",
    slug: "hackathon-electronics-essentials",
    name: "Hackathon Essentials Electronics Kit",
    sku: "KIT-HACK-ESSNTL",
    brand: "Robu",
    categorySlug: "diy-kits",
    price: 79900,
    mrp: 129900,
    inStock: true,
    stock: 96,
    rating: 4.5,
    reviewCount: 310,
    isNew: true,
    description:
      "The 'never scramble at 2am again' kit: jumpers, resistors, LEDs, buzzer, breadboard and modules — every sensor/module builder's base camp.",
    highlights: [
      "Resistors, caps, LEDs & jumpers",
      "2 breadboards + PSU header",
      "Buzzer, buttons, trimmers",
      "USB-C breakout + modules",
    ],
    specs: [
      { label: "Resistors", value: "300 (43 values)" },
      { label: "Capacitors", value: "60 assorted" },
      { label: "LEDs", value: "40 mixed colours" },
      { label: "Boards", value: "2 breadboards" },
      { label: "Extras", value: "Buzzer, buttons, trimmers" },
    ],
    tags: ["hackathon", "kit", "essentials", "breadboard", "maker"],
    imageHue: "from-teal-400 to-emerald-600",
    emoji: "📦",
  },
  {
    id: "p-kit-004",
    slug: "stem-science-learning-kit",
    name: "STEM Science Learning Kit (180 modules)",
    sku: "KIT-STEM-180",
    brand: "Robu",
    categorySlug: "diy-kits",
    price: 499900,
    mrp: 799900,
    inStock: true,
    stock: 28,
    rating: 4.8,
    reviewCount: 190,
    webOnly: true,
    description:
      "Lab-in-a-box with 180 projects across physics, chemistry and electronics — for schools, science fairs and hands-on classrooms.",
    highlights: [
      "180 guided experiments",
      "Snap-on modules, no solder",
      "School science-aligned",
      "Teacher manual included",
    ],
    specs: [
      { label: "Projects", value: "180 experiments" },
      { label: "Type", value: "Snap-fit modules" },
      { label: "Subjects", value: "Physics, chem, electronics" },
      { label: "Ages", value: "10+ recommended" },
      { label: "Manual", value: "Student + teacher guides" },
    ],
    tags: ["stem", "science kit", "school", "learning", "180 projects"],
    imageHue: "from-teal-400 to-emerald-600",
    emoji: "📦",
  },

  // ---------- 3D PRINTING ----------
  {
    id: "p-3dp-001",
    slug: "pla-filament-1kg",
    name: "PLA Filament 1.75mm (1kg Spool)",
    sku: "3DP-FIL-PLA-1KG",
    brand: "Robu",
    categorySlug: "3d-printing",
    price: 44900,
    mrp: 79900,
    inStock: true,
    stock: 150,
    rating: 4.5,
    reviewCount: 1120,
    featured: true,
    description:
      "Clean, tangle-free PLA in a sealed spool with ±0.03mm accuracy. Print crisp prototypes without warping or jamming.",
    highlights: [
      "±0.03mm accuracy, 1.75mm",
      "Vacuum-sealed with gel pack",
      "No warp / no clog formula",
      "Available in 18 colours",
    ],
    specs: [
      { label: "Material", value: "PLA" },
      { label: "Diameter", value: "1.75mm (±0.03mm)" },
      { label: "Weight", value: "1kg net" },
      { label: "Printing", value: "200 – 220°C" },
      { label: "Colours", value: "18 options" },
    ],
    tags: ["pla", "filament", "1.75mm", "3d printer", "spool"],
    imageHue: "from-rose-400 to-pink-600",
    emoji: "🗜️",
  },
  {
    id: "p-3dp-002",
    slug: "ender-3-v3-se-printer",
    name: "Ender-3 V3 SE 3D Printer",
    sku: "3DP-PRN-E3V3SE",
    brand: "Creality",
    categorySlug: "3d-printing",
    price: 1899900,
    mrp: 2499900,
    inStock: true,
    stock: 15,
    rating: 4.6,
    reviewCount: 230,
    isNew: true,
    description:
      "Silent, auto-leveling, 180mm/s speed-capable CoreXZ machine for apprentice makers — 220×220×250mm build volume out of the box.",
    highlights: [
      "CR Touch auto-leveling",
      "Silent dual-Z + 32-bit board",
      "180mm/s max speed",
      "220×220×250mm build",
    ],
    specs: [
      { label: "Volume", value: "220 × 220 × 250mm" },
      { label: "Speed", value: "Up to 180mm/s" },
      { label: "Leveling", value: "CR Touch auto" },
      { label: "Extruder", value: "Direct-drive Sprite" },
      { label: "Layer", value: "0.1 – 0.4mm" },
    ],
    tags: ["ender-3", "creality", "3d printer", "v3 se", "friendly"],
    imageHue: "from-rose-400 to-pink-600",
    emoji: "🗜️",
  },
  {
    id: "p-3dp-003",
    slug: "petg-filament-1kg",
    name: "PETG Filament 1.75mm (Transparent)",
    sku: "3DP-FIL-PETG-1KG",
    brand: "Robu",
    categorySlug: "3d-printing",
    price: 54900,
    mrp: 89900,
    inStock: true,
    stock: 110,
    rating: 4.6,
    reviewCount: 540,
    webOnly: true,
    description:
      "Strong, chemical-resistant PETG that beats PLA on durability — perfect for functional parts, enclosures and outdoor prints.",
    highlights: [
      "230 – 250°C print temp",
      "Impact resistant PETG",
      "Food-ish safe options",
      "Minimal odour",
    ],
    specs: [
      { label: "Material", value: "PETG" },
      { label: "Diameter", value: "1.75mm (±0.03)" },
      { label: "Weight", value: "1kg" },
      { label: "Printing", value: "230 – 250°C" },
      { label: "Bed", value: "60 – 70°C" },
    ],
    tags: ["petg", "filament", "strong", "1.75mm", "functional"],
    imageHue: "from-rose-400 to-pink-600",
    emoji: "🗜️",
  },
  {
    id: "p-3dp-004",
    slug: "direct-drive-extruder",
    name: "Direct-Drive Extruder Kit (Titan Cloned)",
    sku: "3DP-EXTR-TITAN",
    brand: "Trianglelab",
    categorySlug: "3d-printing",
    price: 119900,
    mrp: 189900,
    inStock: true,
    stock: 45,
    rating: 4.4,
    reviewCount: 180,
    description:
      "Top-grade Titan-clone direct drive with hardened steel drive gear — flexible filaments (TPU) become a non-event.",
    highlights: [
      "Titan rebadged clone",
      "Direct drive for TPU",
      "Hardened steel gear",
      "All mounts included",
    ],
    specs: [
      { label: "Type", value: "Direct drive" },
      { label: "Gear", value: "Hardened steel" },
      { label: "Asset", value: "Bowden-ready + mount" },
      { label: "Temp sensor", value: "NTC 100k" },
      { label: "Compatible", value: "Creality / generic" },
    ],
    tags: ["extruder", "direct drive", "titan", "tpu", "upgrade"],
    imageHue: "from-rose-400 to-pink-600",
    emoji: "🗜️",
  },
];

export const brandNames = Array.from(new Set(products.map((p) => p.brand))).sort();

export function getCategories() {
  return categories;
}

export function getCategory(slug: string): Category | undefined {
  return categories.find((c) => c.slug === slug);
}

export function getProduct(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug);
}

export function getProductsByCategory(slug: string): Product[] {
  return products.filter((p) => p.categorySlug === slug);
}

export function getFeaturedProducts(): Product[] {
  return products.filter((p) => p.featured);
}

export function getNewProducts(): Product[] {
  return products.filter((p) => p.isNew);
}

export function getRelatedProducts(product: Product, limit = 4): Product[] {
  return products
    .filter((p) => p.categorySlug === product.categorySlug && p.id !== product.id)
    .slice(0, limit);
}

export function searchProducts(query: string): Product[] {
  const q = query.trim().toLowerCase();
  if (!q) return [];
  return products.filter(
    (p) =>
      p.name.toLowerCase().includes(q) ||
      p.brand.toLowerCase().includes(q) ||
      p.sku.toLowerCase().includes(q) ||
      p.tags.some((t) => t.includes(q))
  );
}